language: cpp

jobs:
  include:
    - os: linux
      compiler:
       - gcc
      addons:
        apt:
          packages:
            - libx11-dev
            - libgl1-mesa-dev
            - libglu1-mesa-dev
      script: make -f makefile.gcc
    - os: osx
      compiler:
       - clang
      script: make -f makefile.osx
    - os: linux
      compiler: 
        - gcc
      addons:
        apt:
          packages:
            - libx11-dev
            - libgl1-mesa-dev
            - libglu1-mesa-dev
      script: cd tests && . ./tests_linux.sh yes
    - os: windows
      language: cpp
      env:
      - MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
      script: 
      - dir "c:\Program Files (x86)\""
      - dir  "c:\Program Files (x86)\Microsoft Visual Studio\"
      - export PATH=$MSBUILD_PATH:$PATH
      - msbuild ng.msbuild /p:configuration=release
