language: cpp
branches:
  only:
    - ng-test-2.2
jobs:
  include:
    - os: linux
      compiler:
       - gcc
      addons:
        apt:
          packages:
            - libx11-dev
            - libgl1-mesa-dev
            - libglu1-mesa-dev
      script: make -f makefile.gcc
    - os: osx
      compiler:
       - clang
      script: make -f makefile.osx
    - os: linux
      compiler: 
        - gcc
      addons:
        apt:
          packages:
            - libx11-dev
            - libgl1-mesa-dev
            - libglu1-mesa-dev
      script: cd tests && . ./tests_linux.sh yes
