#sample osx makefile for test application
CXX=g++
CFLAGS=-I.. -Wall -Wextra -Wno-unused-parameter 
LDFLAGS= -lX11 -lrt
OUT=test.elf
all:
		$(CXX) $(CFLAGS) *.cpp -o $(OUT)  $(LDFLAGS) 
vulkan:
		$(CXX) $(CFLAGS) test_vulkan.cpp -o $(OUT)  $(LDFLAGS)  -lvulkan
